use sys;
CREATE TABLE EMPLOYEE(
 CODE CHAR(4) NOT NULL,
 NAME CHAR(10) NOT NULL,
 DESIGNATION CHAR(30) NOT NULL,
 DOB DATE NOT NULL,
 SALARY NUMERIC NOT NULL,
 PRIMARY KEY(CODE)
 );
 
 INSERT INTO EMPLOYEE
 VALUES ('e1','ANU','HOD','1979-01-16','50000'),
		('e2','AHAM','STAFF','1986-12-30','25000');
        
SELECT *FROM EMPLOYEE;

UPDATE EMPLOYEE SET SALARY='60000' WHERE CODE='e1';

DELETE FROM EMPLOYEE WHERE CODE='e2';
SELECT *FROM EMPLOYEE;
